### PR TITLE
generated nameSuffix from subscription,evcode,& location

### PR DESCRIPTION
**Pull request by sjyang18**
generated nameSuffix from subscription,namingprefix,environmentTag,& location.  This addresses the issue #74 and #75

### CODE REVIEW

**Comment by sushilkm** [comment]
We would need to update the shell scripts in test directory to find the synapse workspace name.

```
- check-pipeline-status.sh
- deploy-prepare-and-test-pipeline.sh
- use-pre-provisioned-batch-account.sh
```

**Comment by sjyang18** [comment]
> resolved

**Comment by sjyang18** [comment]
> We would need to update the shell scripts in test directory to find the synapse workspace name.
> 
> ```
> - check-pipeline-status.sh
> - deploy-prepare-and-test-pipeline.sh
> - use-pre-provisioned-batch-account.sh
> ```

resolved

**Comment by sushilkm** [comment]
It works!!! Thanks @sjyang18 for looking into this.

**Review by sushilkm — APPROVED** [review]

**Review by ivo-andreev — COMMENTED** [review]
The solution appears credible with the utilization of subscription to guarantee uniqueness. Please note that I have rights to only comment but not to approve (which you may imply by voting).

**Review by ivo-andreev — COMMENTED** [review]
You seem to have also addressed the minimum amount of Synapse nodes, which was reported in another issue, thanks.

**Pull request merged**
